version: "3.1"
services:
  backend:
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: sh -c "npx sequelize-cli db:migrate && node index.js"
